# config/config.yaml

product_name: 'bottle'
active_model_architecture: 'unet' 

unet:
  model_config:
    model_type: 'segmentation'
    architecture: 'unet'
    # n_classes will be determined dynamically from each dataset's labels.json
    n_classes: 4 # Placeholder, will be overridden
    n_channels: 3
  train_params:
    learning_rate: 0.0001
    batch_size: 4
    num_epochs: 75
    patience: 15
  paths:
    best_model: 'models/final/best_unet_multiclass_model.pth'
    checkpoint: 'models/checkpoints/latest_unet_multiclass.pth'

deeplabv3plus:
  model_config:
    model_type: 'segmentation'
    architecture: 'deeplabv3plus'
    num_classes: 4 # Placeholder, will be overridden
    output_stride: 16
    pretrained: true
  train_params:
    learning_rate: 0.001
    batch_size: 2
    num_epochs: 75
    patience: 15
  paths:
    best_model: 'models/final/best_deeplabv3_multiclass_model.pth'
    checkpoint: 'models/checkpoints/latest_deeplabv3_multiclass.pth'
